"""Configuration file manager — read, write, and render .conf files."""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from app.constants import TEMPLATES_DIR
from models.server_profile import ServerProfile
from services.log_service import get_log


class ConfigManager:
    """Read/write WoW server .conf files using Jinja2 templates."""

    def __init__(self):
        self._log = get_log()

    def render_conf(self, template_name: str, profile: ServerProfile) -> str:
        """Render a .conf.template with profile values."""
        template_path = TEMPLATES_DIR / template_name
        if not template_path.exists():
            self._log.warning(f"Template not found: {template_name}")
            return ""
        try:
            from jinja2 import Environment, FileSystemLoader, StrictUndefined
            env = Environment(
                loader=FileSystemLoader(str(TEMPLATES_DIR)),
                undefined=StrictUndefined,
                keep_trailing_newline=True
            )
            tpl = env.get_template(template_name)
            return tpl.render(profile=profile, net=profile.network_config, db=profile.db_config)
        except Exception as e:
            self._log.error(f"Template render failed: {e}")
            return ""

    def write_conf(self, content: str, output_path: Path) -> bool:
        try:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(content, encoding="utf-8")
            self._log.info(f"Wrote {output_path.name}")
            return True
        except Exception as e:
            self._log.error(f"Write failed: {e}")
            return False

    def read_conf(self, path: Path) -> dict[str, str]:
        """Parse a key = value conf file into a dict, ignoring comments."""
        result = {}
        if not path.exists():
            return result
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                result[key.strip()] = val.strip()
        return result

    def update_key(self, path: Path, key: str, value: str) -> bool:
        """Update a single key in an existing .conf file."""
        if not path.exists():
            self._log.error(f"Config not found: {path}")
            return False
        content = path.read_text(encoding="utf-8", errors="replace")
        pattern = re.compile(rf"^({re.escape(key)}\s*=\s*).*$", re.MULTILINE)
        if pattern.search(content):
            new_content = pattern.sub(rf"\g<1>{value}", content)
        else:
            new_content = content + f"\n{key} = {value}\n"
        path.write_text(new_content, encoding="utf-8")
        return True

    def generate_worldserver_conf(self, profile: ServerProfile, output_path: Path) -> bool:
        db = profile.db_config
        net = profile.network_config
        lines = [
            "################################################################################",
            "# World Server Configuration — Generated by One Click Server Forge",
            "################################################################################",
            "",
            f"DataDir = \"{Path(profile.install_dir) / 'Data'}\"",
            f"LogsDir = \"\"",
            f"LoginDatabaseInfo = \"{db.host};{db.port};{db.user};{db.password};{db.auth_db}\"",
            f"WorldDatabaseInfo  = \"{db.host};{db.port};{db.user};{db.password};{db.world_db}\"",
            f"CharacterDatabaseInfo = \"{db.host};{db.port};{db.user};{db.password};{db.characters_db}\"",
            "",
            f"RealmID = 1",
            f"GameType = 0",
            f"RealmZone = 1",
            "",
            f"WorldServerPort = {net.world_port}",
            f"BindIP = \"{net.bind_ip}\"",
            "",
            f"PlayerLimit = 100",
            f"MaxPingTime = 30",
            "",
            "# SOAP",
            f"SOAP.Enabled = {1 if net.soap_enabled else 0}",
            f"SOAP.IP = \"127.0.0.1\"",
            f"SOAP.Port = {net.soap_port}",
            "",
            "# RA (Remote Access)",
            f"Ra.Enable = {1 if net.ra_enabled else 0}",
            f"Ra.Port = {net.ra_port}",
        ]
        return self.write_conf("\n".join(lines), output_path)

    def generate_authserver_conf(self, profile: ServerProfile, output_path: Path) -> bool:
        db = profile.db_config
        net = profile.network_config
        lines = [
            "################################################################################",
            "# Auth Server Configuration — Generated by One Click Server Forge",
            "################################################################################",
            "",
            f"LoginDatabaseInfo = \"{db.host};{db.port};{db.user};{db.password};{db.auth_db}\"",
            "",
            f"RealmServerPort = {net.auth_port}",
            f"BindIP = \"{net.bind_ip}\"",
        ]
        return self.write_conf("\n".join(lines), output_path)
